### ISSUE TITLE
fix single dist bento

### ISSUE THREAD

**Issue by cournape** [cournape/Bento#112]
Traceback (most recent call last):
  File "/Users/cournape/src/projects/bento/bento-git/bentomaker", line 103, in <module>
    import bentomakerlib.bentomaker
  File "/Users/cournape/src/projects/bento/bento-git/.bentomaker-0.1-c15061a5bc243fb60ae303b3456a3dc1/bentomakerlib/bentomaker.py", line 11, in <module>
    from bento.utils.utils \
ImportError: No module named utils.utils

**Comment by cournape** [comment]
Fixed in 1a159882c876a0be7ebe5eda35d294cfadab6ff0
