### ISSUE TITLE
Fix python setup.py --help-commands

### ISSUE THREAD

**Issue by cournape** [cournape/Bento#73]
On v0.0.7, we have the following problem:

``` sh
Standard commands:
  build             build everything needed to install
  build_py          "build" pure Python modules (copy to build directory)
  build_ext         build C/C++ extensions (compile/link to build directory)
Traceback (most recent call last):
  File "setup.py", line 12, in <module>
    setuptools.setup()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 138, in setup
    ok = dist.parse_command_line()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/dist.py", line 271, in parse_command_line
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 464, in parse_command_line
    if self.handle_display_options(option_order):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 669, in handle_display_options
    self.print_commands()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/dist.py", line 405, in print_commands
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 740, in print_commands
    max_length)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 706, in print_command_list
    klass = self.get_command_class(cmd)
  File "/Users/david/src/projects/bento/bento-git/bento/distutils/dist.py", line 66, in get_command_class
    raise ValueError("Command %s is not supported by bento.distutils compat layer" % command)
ValueError: Command build_clib is not supported by bento.distutils compat layer
```

**Comment by cournape** [comment]
Fixed in 4311f51bb47a24f8cce94a6e1b96aac74c596155
